<!DOCTYPE html>
<html lang="en">

<title>PHYS-S12: Intro to Digital Fabrication </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="../style.css" rel="stylesheet">


<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div style="align-items: left; justify-content:left;" class="container-fluid">
    <h3 class="nav-title"> PHYS-S12: Intro to Digital Fabrication</h3>
    <div class="navbar-nav">
      <h4></h4>
      <h4><a class="nav-link" href="../index.html">Home</a></h4>
      <h4><a class="nav-link" href="../about.html">About</a></h4>
    </div>
  </div>

</nav>

<body>

<xmp style="display:none;">
<br> 

#### Week 2: CAD and Laser Cutter


<div class="myDiv" style><h3>Press Fit Circle</h3></div>
<div class="vidDiv">
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclestep1.png" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclestep2.png" width=600px alt=PressFitCircle>
        <div class="myDiv">
            First make a sketch with a circle that has the diameter of 40 mm. Then draw a construction line thorugh the circle
        </div>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclestep3.png" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclestep4.png" width=600px alt=PressFitCircle>
         <div class="myDiv">
            Then, make parameters through modify -> change parameters. Make one for the Diameter (40 mm), Notch Height (Diameter/6), and thickness (3.6 mm to adjust to the laser cutter kerf). Then start making a 2 point rectangle from an edge where the circle and contruction line intersect. The rectangle should have the length as notch height and width as thickness/2
        </div>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclestep5.png" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclestep6.png" width=600px alt=PressFitCircle>
        <div class="myDiv">
            Then mirror the rectangle over the construction line
        </div>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclestep7.png" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclestep8.png" width=600px alt=PressFitCircle>
        <div class="myDiv">
            Trim out unneeded parts and use a circular pattern to make the rest of the notches
        </div>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclestep9.png" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclefinish.png" width=600px alt=PressFitCircle>
        <div class="myDiv">
            Finally, again trim out unneeded parts and export as dxf for laser cutting
        </div><br>
        <div class="myDiv">
            <h3>Laser cutting process and different constructions</h3>
        </div>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclefinish1.jpg" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclefinish2.jpg" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclefinish3.jpg" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclefinish4.jpg" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclefinish5.jpg" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclefinish6.jpg" width=600px alt=PressFitCircle>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/pressfitcirclefinish7.jpg" width=600px alt=PressFitCircle>
</div><br><br>

<div class="myDiv" style><h3>Light Bulb in Fusion 360</h3></div>
<div class="vidDiv">
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/image2.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep2.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep3.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep4.png"  width=600px  alt=TutorialBulbStep1>
        <div class="myDiv">
            <h4><strong>First make a sketch of a circle that has a diameter of 30 mm and extrude the circle 40 mm. Then make another sketch on zx plane (or on the front of the viewcube)</strong></h4>
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep5.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep6.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep7.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep8.png"  width=600px  alt=TutorialBulbStep1>
        <div class="myDiv">
            Go to Create -> Project/ Include -> Project and create a project. Then click on the top of the cylinder and press ok. Then plot a point 20 mm above and finish the sketch.
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep9.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep10.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep11.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep12.png"  width=600px  alt=TutorialBulbStep1>
        <div class="myDiv">
            Afterwards, Create sphere at the point that was just made and give it a diameter of 61 mm. Join the sphere with cylinder and fillet the edge between the sphere and cylinder 45 mm
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep13.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep14.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep15.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep16.png"  width=600px  alt=TutorialBulbStep1>
         <div class="myDiv">
            Select the bottom most edge and fillet this edge 5 mm (using shortcut 'F')
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep17.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep18.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep19.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep20.png"  width=600px  alt=TutorialBulbStep1>
         <div class="myDiv">
            Select the bottom most face and extrude this face 15 mm (using shortcut 'e'). Then create a thread after selecting the new cylinder body and set the thread type to 'ANSI unified screw threads'
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep21.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep22.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep23.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep24.png"  width=600px  alt=TutorialBulbStep1>
        <div class="myDiv">
            Then uncheck full length, make the length 10 mm, offset 3mm, and keep everything else the same. Select the bottom most edge and chamfer this edge 4 mm
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep25.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep26.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep27.png"  width=600px  alt=TutorialBulbStep1>
        <div class="myDiv">
            Finally do this process once more. So select the bottom most face, extrude the face only 3 mm this time, and chamfer the then bottom most edge only 2 mm this time
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstep28.png"  width=600px  alt=TutorialBulbStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesTutBulb/tutbulbstepfinish.png"  width=600px  alt=TutorialBulbStep1>
        <div class="myDiv">
            At last, right click the bulb portion, select a preffered appearance and <strong>TA -DA!</strong> You have a <strong>finished Light Bulb</strong> in Fusion 360.
            Below is the video tutorial for this light bulb: 
        </div><br>
        <iframe width="420" height="345" src="https://www.youtube.com/embed/dCqYaNXHybk">
        </iframe>
</div> <br><br>

<div class="myDiv" style><h2>Pen in Fusion 360</h2></div>
<div class="vidDiv">
        <div class="myDiv">
            <h3>First Gather Measurements</h3>
        </div> <br>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm1.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm2.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm3.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm4.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm5.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm6.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm7.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm8.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm9.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm10.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm11.jpg"  height=234px  alt=PenMeasurements>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penm12.jpg"  height=234px  alt=PenMeasurements>


<div class="myDiv"> Then start using CAD</div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep1.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep2.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep3.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep4.png"  width=600px  alt=PenStep1>
        <div class="myDiv">
            First make a sketch of a triangle from the left face of the viewcube. The dimensions of this right triangle is 10 mm for the long side, 5.774 mm for the short side, and 11.547 mm for the hypotenuse. Use the mirror function to mirror the triangle across the 10 mm side to make an equilateral, equiangular triangle. <br> <br> Extrude this triangle 84.3 mm after finishing the sketch (using shortcut 'e')
        </div><br>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep5.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep6.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep7.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep8.png"  width=600px  alt=PenStep1>
        <div class="myDiv">
            Make sure to have Shaded with hidden edges on for convenience. Select the sides that are 84.3 mm long and fillet these sides 2.5 mm. Then press ok and move to the right side of the viewcube, or the end of the triangular prism
        </div><br>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep9.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep10.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep11.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep12.png"  width=600px  alt=PenStep1>
        <div class="myDiv">
            Make a sketch on the far end of the the triangular prism and make a circle centered at the center of the filleted triangle and has the diameter of 8.7 mm. Then finish the sketch and select the circular out face and the inner face. Then extrude these faces 36.2 mm away from the prism and join the bodies
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep13.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep14.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep15.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep16.png"  width=600px  alt=PenStep1>
        <div class="myDiv">
            Then, select the the edge of the cylinder and the filleted triangular prism at their intersection and fillet these edges 2.5 mm
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep17.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep18.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep19.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep20.png"  width=600px  alt=PenStep1>
        <div class="myDiv">
            Then move the view cube to the left face and draw a sketch at the front of the pen. Draw a centered circle with diameter of 7.2 mm. Extrude this circle -1.7 mm.
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep21.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep22.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep23.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep24.png"  width=600px  alt=PenStep1>
        <div class="myDiv">
            Then, move this extruded circle 2 mm away from the pen. Then, using the loft tool (Create -> Loft), loft the two opposing faces of the circle and filleted triangle
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep25.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep26.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep27.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep28.png"  width=600px  alt=PenStep1>
        <div class="myDiv">
            then make another sketch on the front face of the viewcube using the measurements in the picture and line tool, finish the sketch, and create a revolve of this sketch around the center line (2nd longest line of the pen tip). Make this revolve a new body
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep29.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep30.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep31.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep32.png"  width=600px  alt=PenStep1>
        <div class="myDiv">
            reach the right end of the view cube and start sketching another circle at the end of the pen. Make the diameter 3.7 mm and extrude this circle 9.2 mm
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep33.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep34.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep35.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep36.png"  width=600px  alt=PenStep1>
        <div class="myDiv">
            Fillet the edge 1.85 mm (of the recently extruded circle) and start making a sketch from the top of the pen
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep37.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep38.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep39.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep40.png"  width=600px  alt=PenStep1>
        <div class="myDiv">
            Make the curved structure at using the fit point spline feature and extrude this structure 4.8 mm. Also move this structure into the pen -0.75 mm
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstep41.png"  width=600px  alt=PenStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/ImagesPenCAD/penstepfinish.png"  width=600>
        <div class="myDiv">
            Finally, choose an appearance by right clicking the different bodies of the pen and <strong>TA-DA!</strong> You have a finished pen in Fusion 360
        </div>
</div><br><br>

<div class="myDiv" style><h3>Apple Watch in Fusion 360</h3></div>
<div class="vidDiv">
    <div class="myDiv">
            <h3>First Gather Measurements</h3>
        </div> <br>
        <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm1.jpg"  height=234px  alt=PenMeasurements>
     <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm2.jpg"  height=234px  alt=PenMeasurements>
      <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm3.jpg"  height=234px  alt=PenMeasurements>
       <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm4.jpg"  height=234px  alt=PenMeasurements>
        <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm5.jpg"  height=234px  alt=PenMeasurements>
         <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm6.jpg"  height=234px  alt=PenMeasurements>
          <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm7.jpg"  height=234px  alt=PenMeasurements>
           <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm8.jpg"  height=234px  alt=PenMeasurements>
            <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm9.jpg"  height=234px  alt=PenMeasurements>
             <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm10.jpg" height=234px  alt=PenMeasurements>
             <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm11.jpg" height=234px  alt=PenMeasurements>
             <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm12.jpg" height=234px  alt=PenMeasurements>
             <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm13.jpg" height=234px  alt=PenMeasurements>
             <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm14.jpg" height=234px  alt=PenMeasurements>
             <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm15.jpg" height=234px  alt=PenMeasurements>
             <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/Watchm16.jpg" height=234px  alt=PenMeasurements>

<div class="myDiv"> Then start using CAD</div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep1.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep2.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep3.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep4.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            First make a center rectangle with the length of 41 mm and width of 47.5 mm. Then extrude this rectangle 11.2 mm. Flip to the bottom of the cube and start a sketch on the bottom side. Draw a centered circle with a diameter of 24.6 mm 
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep5.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep6.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep7.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep8.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Extrude the circle -2.7 mm and change the view using the viewcube. Select the outer circular edge (the edge not touching anything) and fillet this edge 10 mm.
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep9.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep10.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep11.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep12.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Select the bottom 4 edges of the extruded rectangle (the watch body) and fillet these edges 4 mm. Also fillet the top edges of the watch body 6 mm.
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep13.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep14.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep15.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep16.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Select the corners of the watch body and fillet these 2 mm. Then select the top face of the watch body and extrude it -0.75 mm, cutting into the filleted rectangular prism. Then make a sketch from the top. Make a line that 129.4 mm long and is 13 to 13.5 mm from the x-axis.
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep17.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep18.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep19.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep20.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Then draw a construction line down to the x axis from the end of the 129.4 mm line. Then draw 11.2 mm construction away from the other lines on x-axis. Then select the fit point spline and draw a outward curved line down to the x-axis to meet the end of the 11.2 mm line.
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep21.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep22.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep23.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep24.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Delete all construction lines and draw a large construction line at the x-axis. Select all the lines of the sketch and mirror them over the construction line using the mirror feature. Then, about 30 mm from the end of the fit point spline, make a centered circle with a 4 mm diameter. <br><br> Note: If a shape has not been made yet, connect your last point with your first point to make a closed shape.
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep25.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep26.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep27.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep28.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Continue making these circles, with their centers 8 mm away, until there are 7 holes. Then finish the sketch, extrude the sketch 2 mm, and move the sketch up 4 mm. Then start a new sketch at the other side of the watch body (so left of the watch body looking from the top).
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep29.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep30.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep31.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep32.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Make a 44 mm line 13 to 13.5 mm away from the x-axis (the red axis). Then make 12.3 mm construction line from the 44 mm line. Then make a 19.5 mm non-construction (normal) line from the mentioned construction line, and finally finish off these steps with 2 construction lines, one going down to the x-axis and one, which is a straight line on the x-axis, going 11.2 mm away from all the other lines
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep33.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep34.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep35.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep36.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Then select the fit point spline and make an outward curve down to the x-axis like before with the other wristband
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep37.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep38.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep39.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep40.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Zoom in on the 12.3 mm construction line and select the fit point spline. Remove the construction line a make a small hump that is a few millimeters tall. Then draw a large construction line on the x- axis, select all the other lines of the sketch, and mirror the lines over the construction line. Remember to connect the last point and first point to make a shape
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep41.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep42.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep43.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep44.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Then make an ellipse at the midpoint of the crests of the humps that is 27.6 mm tall and 6 mm wide
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep45.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep46.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep47.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep48.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Finish the sketch and extrude the shape 2 mm. Then move the mentioned extruded sketch up 4 mm.
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep49.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep50.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep51.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep52.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            <strong>FINAL STRETCH!</strong> make 2 concentric circles, centered 12.5 mm away from the end of the wristband. One with a diameter of 3.7 mm and the other with a diameter of 10.8 mm. And then extrude this sketch a small amount (0.2 mm) as a new body. Then select the sphere from the create dropdown.
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep53.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep54.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep55.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep56.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Make a sphere with a diameter of 5 mm at the center of the extruded concentric circles and move this sphere up 3.5 mm. Then select automated modeling and select the sphere and "washer" for 'faces to connect'
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep57.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep58.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep59.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep60.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Select the wristband for 'bodies to avoid' and then wait to pick the most suitable option (In this case, Alternative 6 at the lowest volume)
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep61.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep62.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstep63.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            Finally (Yes this is the end), press the eyeball for body 1 to make invisible (press it again to make it visible) and make a final sketch at back of the viewcube (zx plane). Make a centered circle with a 7 mm diameter with its center 11 mm away the right wristband (see image). Then make an ellipse that has its center 13 mm from the left wristband that is 12 mm wide and 4.5 mm tall. <br><br> Extrude these ellipses 21 mm, make the watch body visible again, and you are done
        </div>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstepfinish1.png"  width=600px  alt=AppleWatchStep1>
    <img src = "https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/AppleWatchCAD/watchstepfinish2.png"  width=600px  alt=AppleWatchStep1>
        <div class="myDiv">
            For asthetics, right click and select appearance for colors on the watch. So, <strong>TA-DA!</strong> You have created an apple watch in Fusion 360.
        </div>
</div> <br> <br>

<div class="myDiv" style><h3>Using the Vinyl Cutter for a Name Tag</h3></div>
<div class="vidDiv">
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/NameSticker/SaiStickerCAD.png"  width=600px  alt=MyNameSticker>
        <div class="myDiv">
            Make a sketch from the top using the fit point spline feature. Draw bubble letters of your liking and finish sketch after connecting the last point to the first point (to complete the shape). Then export as dxf and turn the dxf into an svg using an online converter. Then print to vinyl cutter.
        </div>
        <br>
        <div class="myDiv">
            <h2>The Sticker making process</h2>
        </div>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/NameSticker/SaiStickerFinish1.jpg"  width=600px  alt=MyNameSticker>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/NameSticker/SaiStickerFinish2.jpg"  width=600px  alt=MyNamticker>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/NameSticker/SaiStickerFinish3.jpg"  width=600px  alt=MyNameSticker>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/NameSticker/SaiStickerFinish4.jpg"  width=600px  alt=MyNameSticker>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/NameSticker/SaiStickerFinish5.jpg"  width=600px  alt=MyNameSticker>
</div><br><br>



<div class="myDiv" style><h3>Week 3: Kinetic Sculptures</h3></div>
<div class="vidDiv">
  
  
  <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4095.JPG" width=500px alt=KineticSculpture>
  <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4191.JPG" width=500px alt=KineticSculpture>
  <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4186.JPG" width=500px alt=KineticSculpture>
  
  <div class="myDiv">
    I first tried to use gears, but in my case, they were cluncky and didn't fit well together. I also could not get the gears to work at a 90 degree angle so that the wheels could turn. 
  </div>
  
  <br>

 <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4127.JPG" width=500px alt=KineticSculpture>
 
  
  <div class="myDiv">
    Then after abandoning the gears idea, I was going to directly power the front wheel as my second prototype. In Fusion 360, I made a few circles for a base and wheels. <br> <strong> Add dimensions </strong>
  </div>
  
  <br>
  
  <div class="myDiv">
    <h3> <strong> Laser Cutting Process</strong></h3>
  </div>
  
  <br>

 <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4126.JPG" width=500px alt=KineticSculpture>
  <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4097.JPG" width=500px alt=KineticSculpture>

  
  <div class="myDiv">
    <h3> <strong> Assembly </strong> </h3>
  </div>
  
  <br>

   <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4174.JPG" width=500px alt=KineticSculpture>
  <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4176.JPG" width=500px alt=KineticSculpture>


  <div class="myDiv">
    First, the press fit rectangles along with additional rectangles for support were added
  </div>
  
  <br>

   <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4175.JPG" width=500px alt=KineticSculpture>
   <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4178.JPG" width=500px alt=KineticSculpture>

    
  <div class="myDiv">
    Next, a hole was drilled throught the the middle for wiring. Then the motor on the front wheels was placed. And finally, the back wheels were placed with the failed gear as a stopper to stop the wheels from falling off.
  </div>
  
  <br>

   <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4183.JPG" width=500px alt=KineticSculpture>
   <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4185.JPG" width=500px alt=KineticSculpture>
   <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4186.JPG" width=500px alt=KineticSculpture>

  
  <div class="myDiv">
    Lastly, the guard rails/ more rectangles to keep electronics safe were added and the elctronics were placed in.
  </div>
  
  <br>
  
  <div class="myDiv">
    Multimeter
  </div>

  <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4194.JPG" width=500px alt=KineticSculpture>
    <img src="https://raw.githubusercontent.com/SaiDBod/PHYS-S12-IntroToDigitalFabrication/main/02_CAD/PressFitCircle/IMG-4198.JPG" width=500px alt=KineticSculpture>

  
  
  
</div>
</xmp>


</body>

<script src="../strapdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>

</html>
